# 1. Revese a string

In [4]:
s1="Dheeraj"
s2=s1[::-1]
print(s2)

jareehD


In [5]:
s1="Dheeraj"
s2=""
for i in s1:
    s2=i+s2
print(s2)

jareehD


# 2. Frequency of chracters

In [6]:
s1="Dheeraj"
s2=""
for i in s1:
    if i not in s2:
        s2=s2+i
f=dict()
for i in s2:
    f.update({i:s1.count(i)})
print(f)

{'D': 1, 'h': 1, 'e': 2, 'r': 1, 'a': 1, 'j': 1}


In [7]:
"""
2. Find Frequency of chracters in a string
    i/p : Dheeraj
    o/p : D:1, h:1 ,e:2, r:1, a:1, j:1

    i/p: Ashwini Patil
    o/p : A:1,s:1, h:1, w:1, i:3, n:1, P:1, a:1, t:1 l:1
"""

'\n2. Find Frequency of chracters in a string\n    i/p : Dheeraj\n    o/p : D:1, h:1 ,e:2, r:1, a:1, j:1\n\n    i/p: Ashwini Patil\n    o/p : A:1,s:1, h:1, w:1, i:3, n:1, P:1, a:1, t:1 l:1\n'

In [8]:
s1="Dheeraj"
freq=dict()
print("Before removing duplicate characters : ",s1)
s2=""
for i in s1:
    if i not in s2:
        s2=s2+i
    else:
        pass
print("After removing duplicate characters : ",s2)

for i in s2:
    cnt=s1.count(i)
    freq.update({i:cnt})
print(freq)


Before removing duplicate characters :  Dheeraj
After removing duplicate characters :  Dheraj
{'D': 1, 'h': 1, 'e': 2, 'r': 1, 'a': 1, 'j': 1}


In [9]:
s1="Aswini Patil"
freq=dict()
s2=""

for i in s1:
    if i not in s2 :
        s2=s2+i
    else:
        pass

for i in s2:
    if i !=" ":
         freq.update({i:s1.count(i)})
print(s2," : ",freq)

Aswin Patl  :  {'A': 1, 's': 1, 'w': 1, 'i': 3, 'n': 1, 'P': 1, 'a': 1, 't': 1, 'l': 1}


# 3. Maximum frequency of a character

In [10]:
s1="Dheeraj"
s2=""
for i in s1:
    if i not in s2:
        s2=s2+i
l1=list()
for i in s2:
    l1.append(s1.count(i))
print(l1)
print(max(l1))

[1, 1, 2, 1, 1, 1]
2


In [11]:
s1="Dheeraj"
s2=""
for i in s1:
    if i not in s2:
        s2=s2+i
d1=dict()
for i in s2:
    d1.update({i:s1.count(i)})
print(d1)
print(max(d1,key=d1.get),":",max(d1.values()))

{'D': 1, 'h': 1, 'e': 2, 'r': 1, 'a': 1, 'j': 1}
e : 2


# 4. Sort the list

In [12]:
l1=[1,7,2,6,4,5,3]
l1.sort()
print(l1)

[1, 2, 3, 4, 5, 6, 7]


In [13]:
l1=[1,1,7,2,6,4,6,5,3]
for i in range(len(l1)):
    for j in range(len(l1)-i-1):
        if l1[j]>l1[j-1]:
            l1[j],l1[j+1]=l1[j+1],l1[j]
print(l1)

[1, 1, 4, 2, 6, 6, 3, 5, 7]


# 5. Merge sorted list

In [14]:
l1=[1,7,2,6]
l2=[4,5,3,2]
l1.extend(l2)
print(l1)
l1.sort()
print(l1)

[1, 7, 2, 6, 4, 5, 3, 2]
[1, 2, 2, 3, 4, 5, 6, 7]


In [15]:
l1=[1,7,2,6]
l2=[4,5,3,2]
l1.extend(l2)
for i in range(len(l1)):
    for j in range(len(l1)-i-1):
        if l1[j]>l1[j+1]:
            l1[j],l1[j+1]=l1[j+1],l1[j]
print(l1)

[1, 2, 2, 3, 4, 5, 6, 7]


In [16]:
import numpy as np
l1=[1,7,2,6]
l2=[4,5,3,2]
l1=np.concatenate((l1,l2))
l1.sort()
print(l1)

[1 2 2 3 4 5 6 7]


In [17]:
import numpy as np
l1=[1,7,2,6]
l2=[4,5,3,2]
l1=np.concatenate((l1,l2))
for i in range(len(l1)):
    for j in range(len(l1)-i-1):
        if l1[j]>l1[j+1]:
            l1[j],l1[j+1]=l1[j+1],l1[j]
print(l1)

[1 2 2 3 4 5 6 7]


# 6. Find and add Missing number in an array

In [18]:
l1=[1,7,2,6]
l2=list()
for i in range(min(l1),max(l1)):
    if i not in l1:
        print(i,end=' ')
        l2.append(i)
print()
l1.extend(l2)
print(l1)

3 4 5 
[1, 7, 2, 6, 3, 4, 5]


# 7. Rotate a matrix in an Array, 90 degree

In [19]:
import numpy as np
arr2d_1=[[1,2],[3,4]]
arr2d_2=[[3,1],[4,2]]
np.array(arr2d_1)

array([[1, 2],
       [3, 4]])

In [20]:
import numpy as np
arr2d_1 = [[1, 2], [3, 4]]
arr2d_1 = np.array(arr2d_1)
transposed = arr2d_1[::-1]
rotated = transposed.T
print(rotated)

[[3 1]
 [4 2]]


In [21]:
import numpy as np
arr2d_1 = [[1, 2], [3, 4]]
arr2d_1 = np.array(arr2d_1)
transposed = arr2d_1.T
rotated = transposed[::-1]
print(rotated)


[[2 4]
 [1 3]]


In [22]:
import numpy as np
arr=[[1,2],[3,4]]
arr=np.array(arr)
print(arr,'\n')
arr=arr.T
arr=arr[::-1]
print(arr)

[[1 2]
 [3 4]] 

[[2 4]
 [1 3]]


In [23]:
import numpy as np
arr=[[1,2],[3,4]]
arr=np.array(arr)
print(arr,'\n')
arr=arr[::-1]
arr=arr.T
print(arr)

[[1 2]
 [3 4]] 

[[3 1]
 [4 2]]


# 8. String palindrome

In [24]:
s1="madam"
s2=s1[::-1]
p= s1==s2
print(p)

True


# 9. n-th largest element

In [25]:
l1=[1, 7, 2, 6, 3, 4, 5]
l1.sort()
n=2#int(input())
print(l1)
ele=l1[n]
print(f'At index: {n} , Element: {ele}')

[1, 2, 3, 4, 5, 6, 7]
At index: 2 , Element: 3


# 10. Binary search

In [26]:
def binary_search(arr, target):
    low, high = 0, len(arr) - 1
    while low <= high:
        mid = low + (high - low) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] > target:
            high = mid - 1
        else:
            low = mid + 1
    return -1

# Example usage
arr = [1, 3, 5, 7, 9, 11, 13, 15]
target = 7
result = binary_search(arr, target)
print(f"Target {target} found at index: {result}")


Target 7 found at index: 3


In [27]:
arr = [1, 3, 5, 7, 9, 11, 13, 15]
target = 7
indexpos=-1
low=0
high=len(arr)-1

while(low<=high):
    mid=low+(high-low)//2
    if(target==arr[mid]):
        indexpos=mid
        break
    elif(target<arr[mid]):
        high=mid-1
    else:
        low=mid+1
        
if(indexpos!=-1):
    print(f"{target} at position {indexpos}")
else:
    print("element not found")

7 at position 3


In [28]:
arr = [1, 3, 5, 7, 9, 11, 13, 15]
target = 7
indexpos=-1
low=0
high=len(arr)-1

while(low<=high):
    mid=low+(high-low)//2
    if(target==arr[mid]):
        indexpos=mid
        break
    elif(target<arr[mid]):
        high=mid-1
    else:
        low=low+1
if(indexpos!=-1):
    print(f"{target} is at position {indexpos}")
else:
    print("element not found")

7 is at position 3


# 11. Fibonacci Series

In [29]:
a=0
b=1
l1=list()
l1.extend([a,b])
for i in range(2,10):
    l1.append(a+b)
    a,b=b,a+b
print(l1)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [30]:
def f1(n):
    if n==0:
        return 0
    elif n==1:
        return 1
    else:
        return f1(n-1)+f1(n-2)
    
def f2():
    for i in range(10):
        res=f1(i)
        print(res,end=' ')

f=f2()
f

0 1 1 2 3 5 8 13 21 34 

# 12. Anagrams in a Striing

# 13. Count Inversions i<j and a[i]>a[j]

# 14. Longest Substring without repeating chracters

# 15. Find the First Non-Repeating Character

In [31]:
s="Dheeraj Dreh"
for i in s:
    if s.count(i)==1:
        print(i)

a
j
 


# 16. Find Duplicate in an String

In [32]:
s1="Dheeraj Chandan"
s2=""
for i in s1:
    if s1.count(i)>1 and i not in s2:
        s2=s2+i
        print((i,s1.count(i)),end=' ')

('h', 2) ('e', 2) ('a', 3) ('n', 2) 

# 17. Decorator

In [33]:
def func1(f1):
    def wrapper():
        print(f1())
    return wrapper

@func1
def func2():
    return "Dheeraj"

res=func2()
res


Dheeraj


# 18. Generator  and Yield

In [34]:
def f():
    yield "Hi"
    yield "My name is"
    yield "Dheeraj"

res1=f()
for i in res1:
    print(i)

res2=f()
res2=[i for i in res2]
res2


Hi
My name is
Dheeraj


['Hi', 'My name is', 'Dheeraj']

In [35]:
def fib(limit):
    a, b = 0, 1
    while b < limit:
        yield b
        a, b = b, a + b

x = fib(10)

for i in x:
    print(i,end=' ')

1 1 2 3 5 8 

# 19. Lambda

In [36]:
def func(a,b):
    return a*b
res=func(2,4)
print(res)


8


In [37]:
res= lambda a,b : a*b
res(2,4)

8

In [38]:
def f(n):
    f=1
    for i in range(n):
       f=f*(i+1) 
    return f
res=f(5)
print(res)

120


In [39]:
res=lambda n: [i for i in range(n)]
res(5)

[0, 1, 2, 3, 4]

# 20. Yield

In [40]:
def func(n):
    for i in range(n):
        print(i,end=' ')
res=func(5)
res

0 1 2 3 4 

In [41]:
def func(n):
    for i in range(n):
        yield i
res=func(5)
for i in res:
    print(i,end=' ')

0 1 2 3 4 

In [42]:
def myFunc():
  yield "Hello"
  yield 51
  yield "Good Bye"

x = myFunc()

for z in x:
  print(z)

Hello
51
Good Bye


# 21. OOPs

In [43]:
# Overriding
class Animal():
    def sound(self):
        print("Make Sound")

class Dog(Animal):
    def sound(self):
        print("Bhoww")
class Cat(Animal):
    def sound(self):
        print("Mewoo")

d=Dog()
c=Cat()
d.sound()
c.sound()

Bhoww
Mewoo


In [44]:
# Overloading
class Add():
    def calc(self,*args):
        print(sum(args))

c=Add()
c.calc(1,2,3)
c.calc(4,5,6)

6
15


In [45]:
# Inheritance
class Animal():
    def __init__(self,s):
        self.s=s
    def sound(self):
        print(self.s)

class Dog(Animal):
    def __init__(self,s):
        super().__init__(self)
        self.s=s
    def sound(self):
        print(self.s)
class Cat(Animal):
    def __init__(self,s):
        super().__init__(self)
        self.s=s
    def sound(self):
        print(self.s)    

d=Dog("Bhoww")
c=Cat("Meww")
d.sound()
c.sound()

Bhoww
Meww


In [46]:
# abstraction
"""
Code in file 1,
def a():
    print("Hi")

code in file 2,
import file1
def b():
    file1.a()
b()
"""

'\nCode in file 1,\ndef a():\n    print("Hi")\n\ncode in file 2,\nimport file1\ndef b():\n    file1.a()\nb()\n'

# 22. MySQL connector

In [47]:
# Normal statement
import mysql.connector
con=mysql.connector.connect(host="localhost",user="root",password="kiit",database="cdac")
cur=con.cursor()

q1="select * from employee_1"
cur.execute(q1)
res=cur.fetchall()
for i in res:
    print(i)

(5, 'Priya Sharma', 'Female', 45000.0, 'IT', 6)
(6, 'Rahul Patel', 'Male', 65000.0, 'Sales', 5)
(7, 'Nisha Gupta', 'Female', 55000.0, 'Marketing', 4)
(8, 'Vikram Singh', 'Male', 75000.0, 'Finance', 7)
(9, 'Aarti Desai', 'Female', 50000.0, 'IT', 4)


In [48]:
# Prepared statement
import mysql.connector 
con=mysql.connector.connect(host="localhost",user="root",password="kiit",database="cdac")
cur=con.cursor()

ch="A"#input()
q1="select * from employee_1 where Name like %s"
cur.execute(q1,(ch+"%",))
res=cur.fetchall()
for i in res:
    print(i)

(9, 'Aarti Desai', 'Female', 50000.0, 'IT', 4)


In [49]:
# Prepared statement
import mysql.connector
con=mysql.connector.connect(host="localhost",user="root",password="kiit",database="cdac")
cur=con.cursor()

ch="A"#input()
st="Aarti Desai"#input()
q1="update employee_1 set Name=%s where Name like %s"
q2="select * from employee_1"
cur.execute(q1,(st,ch+"%"))
changecnt=cur.rowcount
print(changecnt)
con.commit()

cur.execute(q2)
res=cur.fetchall()
for i in res:
    print(i)

0
(5, 'Priya Sharma', 'Female', 45000.0, 'IT', 6)
(6, 'Rahul Patel', 'Male', 65000.0, 'Sales', 5)
(7, 'Nisha Gupta', 'Female', 55000.0, 'Marketing', 4)
(8, 'Vikram Singh', 'Male', 75000.0, 'Finance', 7)
(9, 'Aarti Desai', 'Female', 50000.0, 'IT', 4)


# 23. Intersection of two lists

In [50]:
l1=[1,2,6,4,7,3]
l2=[3,4,5,6,7,8]
l3=list()
for i in l1:
    if i in l2:
        l3.append(i)
print(l3)

[6, 4, 7, 3]


In [51]:
import numpy as np
l3=np.intersect1d(l1,l2)
print(l3)

[3 4 6 7]


# 24. Remove duplicate elements from a list

In [52]:
l1=[1,4,2,6,7,2,4,5]
for i in l1:
    if l1.count(i)>1:
        l1.pop(i)
print(l1)

[1, 4, 6, 2, 5]


# 25. Largest number without using function

In [53]:
l1=[1,4,2,6,7,2,4,5]
maxnum=l1[0]
for i in l1:
    if i>maxnum:
        maxnum=i
print(maxnum)

7


# 26. ip - aBcdE , op - AbCDe

In [54]:
s1="aBcdE"
s2=""
for i in s1:
    if 'a'<=i<='z':
        s2=s2+i.upper()
    elif 'A'<=i<='Z':
        s2=s2+i.lower()
    else:
        pass
print(s1," : ",s2)

aBcdE  :  AbCDe


# 27. Find Duplicate in an Array

In [55]:
s1="Dheeraj Chandan"
s2=""
for i in s1:
    if s1.count(i)>1 and i not in s2:
        s2=s2+i
        print(i)

h
e
a
n


# 28. Intersection of 2 Lists

# 29. ip - aBcdE , op - AbCDe

In [4]:
""" 30. Reverse an array**.
    31. Find the missing number** in an array of size n with values from 1 to n+1.
    32. Find the "K-th" largest element** in an unsorted array.
    33. Find the longest subarray with a given sum**.
    34. Find all pairs in an array that sum up to a specific value**.
    35. Find the longest substring without repeating characters**.
    36. Rotate an array** by a given number of steps"""

' 30. Reverse an array**.\n    31. Find the missing number** in an array of size n with values from 1 to n+1.\n    32. Find the "K-th" largest element** in an unsorted array.\n    33. Find the longest subarray with a given sum**.\n    34. Find all pairs in an array that sum up to a specific value**.\n    35. Find the longest substring without repeating characters**.\n    36. Rotate an array** by a given number of steps'

In [1]:
# Player,Country,sports in a different list

sports_stars_details = {
    "Lionel Messi": 	{"Sport": "Football", "Country": "Argentina"},
    "Roger Federer": 	{"Sport": "Tennis", "Country": "Switzerland"},
    "Michael Jordan": 	{"Sport": "Basketball", "Country": "USA"},
    "Usain Bolt": 	{"Sport": "Athletics", "Country": "Jamaica"},
    "Sachin Tendulkar": {"Sport": "Cricket", "Country": "India"},
    "Serena Williams": 	{"Sport": "Tennis", "Country": "USA"},
    "Cristiano Ronaldo": {"Sport": "Football", "Country": "Portugal"},
    "Tiger Woods": 	{"Sport": "Golf", "Country": "USA"},
    "Lewis Hamilton": 	{"Sport": "Formula 1", "Country": "UK"},
    "Kobe Bryant": 	{"Sport": "Basketball", "Country": "USA"}
}

c=0
l1=list()
l2=list()
l3=list()
for i,j in sports_stars_details.items():
	l1.append(i)			        # Player
	l2.append(j["Sport"])		# Sport			
	l3.append(j["Country"])		# Country
	c=c+1
print("layers : ",l1)
print("Sports : ",l2)
print("Country : ",l3)

layers :  ['Lionel Messi', 'Roger Federer', 'Michael Jordan', 'Usain Bolt', 'Sachin Tendulkar', 'Serena Williams', 'Cristiano Ronaldo', 'Tiger Woods', 'Lewis Hamilton', 'Kobe Bryant']
Sports :  ['Football', 'Tennis', 'Basketball', 'Athletics', 'Cricket', 'Tennis', 'Football', 'Golf', 'Formula 1', 'Basketball']
Country :  ['Argentina', 'Switzerland', 'USA', 'Jamaica', 'India', 'USA', 'Portugal', 'USA', 'UK', 'USA']


In [2]:
import pandas as pd
students = [
    {"name": "Alice", "math": 85, "science": 92, "english": 88},
    {"name": "Bob", "math": 78, "science": 85, "english": 82},
    {"name": "Charlie", "math": 90, "science": 87, "english": 91},
]
std_avg=dict()


def f(data):
    for i in data:                                                  # Get each student data
        stud_name=list()
        marks=list()
        stud_name.append(i["name"])                                 # Get each student name
        marks.extend([i["math"],i["science"],i["english"]])         # Get all 
        print(stud_name)
        print(marks)
        std_avg.update({stud_name[0]:sum(marks)/3})
    print(std_avg)
f(students)                                                         # Passing a Student data


['Alice']
[85, 92, 88]
['Bob']
[78, 85, 82]
['Charlie']
[90, 87, 91]
{'Alice': 88.33333333333333, 'Bob': 81.66666666666667, 'Charlie': 89.33333333333333}


In [4]:
import pandas as pd
students = [
    {"name": "Alice", "math": 85, "science": 92, "english": 88},
    {"name": "Bob", "math": 78, "science": 85, "english": 82},
    {"name": "Charlie", "math": 90, "science": 87, "english": 91},
]
std_avg=dict()
def f(data):
    for i in data: 
        std_avg.update({i["name"]:sum([i["math"],i["science"],i["english"]])/3})
    print(std_avg)
f(students)                                                         # Passing a Student data


{'Alice': 88.33333333333333, 'Bob': 81.66666666666667, 'Charlie': 89.33333333333333}
