### Data Preparation
'''
Load the data
'''

In [2]:
import pandas as pd
# 1. Loading the data
df1=pd.read_csv("winequality-red.csv")
print("DataFrame Column names : ",df1.columns)
print(df1.head())
print(df1.tail())




DataFrame Column names :  Index(['fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"'], dtype='object')
  fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0   7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                                                     
1   7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5                                                                                                                     
2  7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;...                                                                                                                     
3  11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58...                                               

In [3]:
# 2. Label and dataspilt for rearranging in order
import numpy as np
df2=pd.read_csv("winequality-red.csv",sep=';')
#print(df2.head())
#x=df2.drop(["quality"],axis=1) # feature
#y=df2["quality"] # label
y=np.array(df2["quality"])
x=df2.drop(["quality","residual sugar","free sulfur dioxide","pH"],axis=1)
x=np.array(df2[["alcohol","volatile acidity"]])
print(np.array(x).shape)
#print(x.head()) #df2["quality"]
#print(y.head())

(1599, 2)


# Data Cleaning and correlationa and covariance

In [4]:
import numpy as np
print(df2.isnull().sum())
print(list(y))
unique_data=np.unique(y,return_counts=True)
print(unique_data)
val,count=np.unique(y,return_counts=True)
for i in range(len(val)):
    print(val[i],count[i])
print("Corelation : \n",df2.corr())
print("Covariance : \n",df2.cov())

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64
[5, 5, 5, 6, 5, 5, 5, 7, 7, 5, 5, 5, 5, 5, 5, 5, 7, 5, 4, 6, 6, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 6, 6, 7, 4, 5, 5, 4, 6, 5, 5, 4, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 5, 5, 5, 6, 5, 5, 7, 5, 5, 5, 5, 5, 5, 6, 6, 5, 5, 4, 5, 5, 5, 6, 5, 4, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 6, 5, 5, 4, 6, 5, 5, 5, 6, 6, 6, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 5, 5, 5, 5, 5, 7, 5, 5, 5, 5, 6, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 4, 5, 5, 5, 5, 5, 5, 5, 6, 5, 4, 6, 5, 5, 5, 5, 4, 6, 5, 4, 6, 6, 6, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 7, 4, 7, 5, 5, 5, 6, 7, 7, 5, 5, 7, 6, 6, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 5, 6, 4,

# Train Test Split

In [5]:
from sklearn.model_selection import train_test_split
import numpy as np
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
print("Shape of x       : ",np.array(x).shape)
print("Shape of y       : ",np.array(y).shape)
print("Shape of x_train : ",np.array(x_train).shape)
print("Shape of y_train : ",np.array(y_train).shape)
print("Shape of x_test  : ",np.array(x_test).shape)
print("Shape of y_test  : ",np.array(y_test).shape)

Shape of x       :  (1599, 2)
Shape of y       :  (1599,)
Shape of x_train :  (1279, 2)
Shape of y_train :  (1279,)
Shape of x_test  :  (320, 2)
Shape of y_test  :  (320,)


# Model Creation + selection

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
#model=LogisticRegression()
model=SVC()

# Model Training

In [7]:
model.fit(x_train,y_train)

SVC()

# Model Evaluation

In [8]:
print("Model score : ",model.score(x_test,y_test))

Model score :  0.534375


# Model Saving

In [9]:
import pickle
with open("model_file2.pickle","wb") as f:
    pickle.dump(model,f)

# Model loading

In [10]:
import pickle
with open("model_file2.pickle","rb") as f:
    model=pickle.load(f)

# Model Prediction

In [11]:
print(y_test)
print()
y_pred=model.predict(x_test)
print(y_pred)

[5 5 6 5 4 5 6 5 5 6 7 7 5 5 6 6 7 6 6 5 5 4 6 4 6 6 4 7 6 6 6 5 5 5 5 7 7
 5 6 6 6 6 4 5 7 6 6 6 7 5 6 5 5 6 5 5 5 5 6 5 5 5 6 3 5 5 5 5 6 6 6 5 6 7
 5 6 6 7 5 4 5 7 5 5 7 6 6 6 6 5 4 6 5 6 5 6 6 3 5 5 5 6 6 5 6 7 5 5 6 6 6
 6 5 5 5 6 5 6 7 5 7 5 6 6 6 5 4 5 6 8 5 6 4 5 7 6 5 6 6 6 6 7 6 5 5 7 6 5
 7 5 7 5 6 6 5 6 7 5 6 5 6 6 6 6 6 7 6 5 5 5 6 6 5 7 6 5 6 5 5 6 6 6 6 6 5
 6 6 5 5 5 6 6 7 5 5 5 6 4 7 5 5 4 6 6 5 4 5 6 6 6 6 6 5 6 6 6 6 8 5 5 6 5
 6 6 5 5 5 7 6 5 5 4 5 6 6 7 6 5 7 6 6 6 5 7 6 6 5 7 5 5 7 5 5 5 6 6 7 5 5
 6 6 5 6 6 7 6 5 6 8 6 6 6 5 6 5 6 6 6 5 5 5 5 6 6 5 6 4 6 6 5 5 6 6 6 6 7
 6 7 5 7 5 6 5 6 5 5 5 6 5 5 8 7 4 5 5 6 6 5 6 8]

[5 5 6 5 5 5 6 5 5 6 6 6 6 6 6 5 6 6 5 5 5 5 5 6 6 6 6 6 5 5 6 5 5 5 5 6 6
 5 5 5 5 5 5 5 6 6 5 5 5 5 6 6 5 5 6 6 5 5 6 5 6 5 5 5 6 5 5 5 5 6 5 5 6 6
 5 6 5 6 5 5 5 6 5 5 5 6 5 6 6 5 6 6 5 5 5 5 6 5 5 5 5 6 5 5 5 6 5 5 5 5 6
 6 5 6 5 6 6 5 6 6 6 5 5 5 5 5 6 5 5 6 5 6 5 5 6 5 5 5 6 6 5 6 6 5 6 6 6 6
 5 5 6 5 5 6 6 6 6 5 6 5 6 6 6 6 6 6 5 5 5 5 6 5 

In [12]:
import numpy as np
unique_data1=np.unique(y_train,return_counts=True)
print(unique_data1)
val,count=np.unique(y_train,return_counts=True)
for i in range(len(val)):
    print(val[i],' : ',count[i])
print()

unique_data2=np.unique(y_pred,return_counts=True)
print(unique_data2)
val,count=np.unique(y_pred,return_counts=True)
for i in range(len(val)):
    print(val[i],' : ',count[i])

(array([3, 4, 5, 6, 7, 8], dtype=int64), array([  8,  38, 557, 501, 162,  13], dtype=int64))
3  :  8
4  :  38
5  :  557
6  :  501
7  :  162
8  :  13

(array([5, 6], dtype=int64), array([170, 150], dtype=int64))
5  :  170
6  :  150


# K-Fold

In [13]:
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.model_selection import train_test_split
import numpy as np
kf=StratifiedGroupKFold(n_splits=5)

y=np.array(df2["quality"])
x=np.array(df2[["alcohol","volatile acidity"]])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

for train_index,test_index in kf.split(x,y):
    x_train=x[train_index]
    x_test=x[test_index]
    y_train=y[train_index]
    y_test=y[test_index]

    val,count=np.unique(list(y_train),return_counts=True)
    for i in range(len(val)):
        print(val[i],count[i])
    print(np.array(y_train).shape)

    val,count=np.unique(list(y_test),return_counts=True)
    for i in range(len(val)):
        print(val[i],count[i])
    print(np.array(y_test).shape)
    print("-"*20)

#print(np.array(y_train).shape)
#print(np.array(y_test).shape)

3 10
4 53
5 680
6 638
7 199
8 18
(1598,)
5 1
(1,)
--------------------
3 10
4 53
5 681
6 638
7 199
8 18
(1599,)
(0,)
--------------------
3 10
4 53
5 681
6 638
7 199
8 18
(1599,)
(0,)
--------------------
3 10
4 53
5 681
6 638
7 199
8 18
(1599,)
(0,)
--------------------
3 10
4 53
5 681
6 638
7 199
8 18
(1599,)
(0,)
--------------------


In [14]:
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.model_selection import KFold
import numpy as np

#kf = StratifiedGroupKFold(n_splits=5)
kf = KFold(n_splits=5)

y = np.array(df2["quality"])
x = np.array(df2[["alcohol", "volatile acidity"]])
#groups = np.array(df2["group"])  # Assuming you have a 'group' column in your dataframe

for train_index, test_index in kf.split(x, y):
    x_train = x[train_index]
    x_test = x[test_index]
    y_train = y[train_index]
    y_test = y[test_index]

    val, count = np.unique(y_train, return_counts=True)
    for i in range(len(val)):
        print(val[i], count[i])
    print(np.array(y_train).shape)

    val, count = np.unique(y_test, return_counts=True)
    for i in range(len(val)):
        print(val[i], count[i])
    print(np.array(y_test).shape)
    print("-" * 20)


3 10
4 38
5 501
6 537
7 177
8 16
(1279,)
4 15
5 180
6 101
7 22
8 2
(320,)
--------------------
3 8
4 48
5 564
6 495
7 153
8 11
(1279,)
3 2
4 5
5 117
6 143
7 46
8 7
(320,)
--------------------
3 7
4 41
5 527
6 534
7 153
8 17
(1279,)
3 3
4 12
5 154
6 104
7 46
8 1
(320,)
--------------------
3 10
4 43
5 594
6 484
7 135
8 13
(1279,)
4 10
5 87
6 154
7 64
8 5
(320,)
--------------------
3 5
4 42
5 538
6 502
7 178
8 15
(1280,)
3 5
4 11
5 143
6 136
7 21
8 3
(319,)
--------------------


# With train.csv

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
df3=pd.read_csv("train.csv")
#print(df3.head())

x=df3.drop(["Survived"],axis=1)
y=df3["Survived"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

# Get Dummies

In [16]:
import pandas as pd
data={"NAME":["ravi","manu","hari"],
      "DEPT":["sales","purch","accts"]}
df1=pd.DataFrame(data)
print(df1)
print()
# 1 
df2=pd.get_dummies(df1["DEPT"]).set_index(df1["NAME"])
print(df2)
print()

# 2
df3 = df1.copy()
df3['Dept'] = range(1, len(df3) + 1)
print(df3)
print()

# 3
df4 = df3.copy()
df4['Dept'] = df4['Dept'] / 10
print(df4)

   NAME   DEPT
0  ravi  sales
1  manu  purch
2  hari  accts

      accts  purch  sales
NAME                     
ravi      0      0      1
manu      0      1      0
hari      1      0      0

   NAME   DEPT  Dept
0  ravi  sales     1
1  manu  purch     2
2  hari  accts     3

   NAME   DEPT  Dept
0  ravi  sales   0.1
1  manu  purch   0.2
2  hari  accts   0.3


In [17]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
d=["A","E","B","D","C","A"]
data=pd.get_dummies(d)
print(data)
le=LabelEncoder()
print(le.fit_transform(d))

   A  B  C  D  E
0  1  0  0  0  0
1  0  0  0  0  1
2  0  1  0  0  0
3  0  0  0  1  0
4  0  0  1  0  0
5  1  0  0  0  0
[0 4 1 3 2 0]
