In [2]:
'''
.copy() - Return an array copy of the given object.
'''
import numpy as np
a1=np.arange(0,11)
print(a1)
print(a1[7])
print(a1[1:5])
print(a1[0:4])
print(a1[0:6])
print(a1[5:])
a2=a1
print(a2)
a2[2:6]=100
print(a2)
a3=a1[0:6]
print(a3)
a3[:]=3
print(a3)
print(a1)
a4=a1.copy()
print(a4)
a1[2:5]=10
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10]
7
[1 2 3 4]
[0 1 2 3]
[0 1 2 3 4 5]
[ 5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[  0   1 100 100 100 100   6   7   8   9  10]
[  0   1 100 100 100 100]
[3 3 3 3 3 3]
[ 3  3  3  3  3  3  6  7  8  9 10]
[ 3  3  3  3  3  3  6  7  8  9 10]
[ 3  3 10 10 10  3  6  7  8  9 10]


In [26]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print("Elements in 1st row ",b[0])
print("Elements in 2nd row ",b[1])
print(b[0][0])
print(b[0][1])
# It is recommended that to use single coma notation to get n element. 
print(b[1][0],' ',b[1,0])
print(b[1][1],' ',b[1,1])
# To grab elements from an array or get sub array.
print(b[1:2])
print(b[1:3,0:3])
print(b[1:2,1:2])
print(b[::-1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Elements in 1st row  [1 2 3]
Elements in 2nd row  [4 5 6]
1
2
4   4
5   5
[[4 5 6]]
[[4 5 6]
 [7 8 9]]
[[5]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [3]:
# Conditionl selection - 
c=np.arange(10)
print(c)
c1=c<5
print(c1)
print(c[c1])
print(c[c>5])
print(c[c%2==0])
c2=np.array(c1)
print(c2)
print(c[c2==True])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]
[6 7 8 9]
[0 2 4 6 8]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]


In [43]:
d=np.arange(50).reshape(5,10)
print(d)
print(d[1:3,3:5])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[13 14]
 [23 24]]
