In [1]:
'''
NumPy Opertion -
    Array with Array
    Array with scalars
    Universal array functions
'''

'\nNumPy Opertion -\n    Array with Array\n    Array with scalars\n    Universal array functions\n'

In [2]:
import numpy as np
a1=np.arange(0,6)

# vector
print(a1)
print(a1+a1)
print(a1//a1)
print(a1*a1)
'''Numpy will give an warning regarding invalid value encountered in true_divide.'''
"It will return Nan if number 0 dived by any num and inf any number divided by 0."
print(a1/a1)

# scalar 
print(a1+100)
print(a1*10)
print(a1**3)


# Universal array functions: Mathematical array operations
'''
np.sqrt()
np.exp()
np.max()
np.min()
np.sin()
np.cos()
np.log()

'''

[0 1 2 3 4 5]
[ 0  2  4  6  8 10]
[0 1 1 1 1 1]
[ 0  1  4  9 16 25]
[nan  1.  1.  1.  1.  1.]
[100 101 102 103 104 105]
[ 0 10 20 30 40 50]
[  0   1   8  27  64 125]


C:\Users\KIIT\AppData\Local\Temp\ipykernel_17544\3536504070.py:7: RuntimeWarning: divide by zero encountered in floor_divide
  print(a1//a1)
C:\Users\KIIT\AppData\Local\Temp\ipykernel_17544\3536504070.py:11: RuntimeWarning: invalid value encountered in divide
  print(a1/a1)


'\nnp.sqrt()\nnp.exp()\nnp.max()\nnp.min()\nnp.sin()\nnp.cos()\nnp.log()\n\n'

In [3]:
import numpy as np
b = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
for element in b.flat:
    print(element)

0
1
2
10
12
13
100
101
102
110
112
113


In [15]:

'''
                #Trigonometric functions
sin, 
cos, 
tan
arcsin,
arccos,
arctan
arctan2
hypot
sinh,
cosh,
tanh
arcsinh, 
arccosh, 
arctanh
degree 
radians
deg2rad
rad2deg

                #Bit-twiddling functions:
bitwise_and
bitwies_or
bitwise_xor
invert
left_shift
right_shift

                #Comparison functions
greater
greater_equal
less
less_equal
not_equal
equal
logical_and
logical_or
logical_xor
logical_not
maximum
minimum
fmax
fmin



                        #Floating functions
isfinite
isinf
isnan
isnat
fabs
signbit
copysign
nextafter
spacing
modf
ldexp
frexp
fmod
floor
ceil
trunc


#Statistical functions:
amin, amax
ptp
percentile(a, p, axis)
median
mean
std
var
average




                    #Math operations:
add
substract
multiply
matmul
divide
logaddexp
logaddexp2
true_divide
floor_divide
negative
positive
power
float_power
remainder
mod
fmod
divmod
absolute
fabs
rint
sign
heaviside
conj
conjugate
exp
exp2
log
log2
log10
expm1
log1p
sqrt
square
cbrt
reciprocal
gcd
lcm












'''

'\n                #Trigonometric functions\nsin, \ncos, \ntan\narcsin,\narccos,\narctan\narctan2\nhypot\nsinh,\ncosh,\ntanh\narcsinh, \narccosh, \narctanh\ndegree \nradians\ndeg2rad\nrad2deg\n\n                #Bit-twiddling functions:\nbitwise_and\nbitwies_or\nbitwise_xor\ninvert\nleft_shift\nright_shift\n\n                #Comparison functions\ngreater\ngreater_equal\nless\nless_equal\nnot_equal\nequal\nlogical_and\nlogical_or\nlogical_xor\nlogical_not\nmaximum\nminimum\nfmax\nfmin\n\n\n\n                        #Floating functions\nisfinite\nisinf\nisnan\nisnat\nfabs\nsignbit\ncopysign\nnextafter\nspacing\nmodf\nldexp\nfrexp\nfmod\nfloor\nceil\ntrunc\n\n\n#Statistical functions:\namin, amax\nptp\npercentile(a, p, axis)\nmedian\nmean\nstd\nvar\naverage\n\n\n\n\n                    #Math operations:\nadd\nsubstract\nmultiply\nmatmul\ndivide\nlogaddexp\nlogaddexp2\ntrue_divide\nfloor_divide\nnegative\npositive\npower\nfloat_power\nremainder\nmod\nfmod\ndivmod\nabsolute\nfabs\nrint\nsi

In [1]:
'''                #Trigonometric functions'''
import numpy as np

x = np.array([-1, +1, +1, -1])
y = np.array([-1, -1, +1, +1])
print("arctan2  : ",np.arctan2(x,y)) # computes element-wise arc tangent of arr1/arr2 choosing the quadrant correctly.
print("hypot : ",np.hypot(3*np.ones((3, 3)), 4*np.ones((3, 3)))) # To calculate hypotenuse for the right angled triangle
                                                                 # given its side and perpendicular.

s=[i for i in np.arange(0,361,15)]
print(s)
print("Sin of ",s," : ",np.sin(s))              # To find sine of angles
print("arcsinh of ",s,' : ',np.arcsinh(s))      # To calculate inverse hyperbolic sine
print("Cos of ",s," : ",np.cos(s))              # To calculate cosine of angles
print("Tan of ",s," : ",np.tan(s))              # To calculate Tangent of angles
print("arcsin of ",s," : ",np.arcsin(s))        # To calculate inverse sine
print("arccos of ",s," : ",np.arccos(s))        # To calculate inverse cosine
print("arctan of ",s," : ",np.arctan(s))        # To calculate inverse tangent
print("sinh of ",s," : ",np.sinh(s))            # To calculate hyperbolic sine
print("cosh of ",s," : ",np.cosh(s))            # To calculate hyperbolic cosine
print("tanh of ",s," : ",np.tanh(s))            # To calculate hyperbolic tangent
print("arccosh of ",s," : ",np.arccosh(s))      # To calculate inverse hyperbolic cosine
print("arctanh of ",s," : ",np.arctanh(s))      # To calculate inverse hyperbolic tangent
print("degree of ",s," : ",np.degrees(s))       # To find Degrees of angles
print("radians of ",s," : ",np.radians(s))      # To find Radians of angles
print("deg2rad of ",s," : ",np.deg2rad(s))      # To convert degree to radian
print("rad2deg of ",s," : ",np.rad2deg(s))      # To convert radian to degree

arctan2  :  [-2.35619449  2.35619449  0.78539816 -0.78539816]
hypot :  [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360]
Sin of  [0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360]  :  [ 0.          0.65028784 -0.98803162  0.85090352 -0.30481062 -0.38778164
  0.89399666 -0.97053528  0.58061118  0.08836869 -0.71487643  0.99779728
 -0.80115264  0.21945467  0.46771852 -0.93009488  0.94544515 -0.50639163
 -0.17604595  0.77387159 -0.99975584  0.74513326 -0.13238163 -0.54399582
  0.95891572]
arcsinh of  [0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360]  :  [0.         3.40230665 4.09462222 4.4999331  4.78756118 5.01067974
 5.19298771 5.34713021 5.48065628 5.59843568 5.70379359 5.79910184
 5.88611175 5.96615331 6.04026038 6.10925252 6.17379044 6.23441457
 6.

C:\Users\KIIT\AppData\Local\Temp\ipykernel_4020\3484248930.py:16: RuntimeWarning: invalid value encountered in arcsin
  print("arcsin of ",s," : ",np.arcsin(s))        # To calculate inverse sine
C:\Users\KIIT\AppData\Local\Temp\ipykernel_4020\3484248930.py:17: RuntimeWarning: invalid value encountered in arccos
  print("arccos of ",s," : ",np.arccos(s))        # To calculate inverse cosine
C:\Users\KIIT\AppData\Local\Temp\ipykernel_4020\3484248930.py:22: RuntimeWarning: invalid value encountered in arccosh
  print("arccosh of ",s," : ",np.arccosh(s))      # To calculate inverse hyperbolic cosine
C:\Users\KIIT\AppData\Local\Temp\ipykernel_4020\3484248930.py:23: RuntimeWarning: invalid value encountered in arctanh
  print("arctanh of ",s," : ",np.arctanh(s))      # To calculate inverse hyperbolic tangent


In [31]:
''' #Bit-twiddling functions '''
import numpy as np
s=[i for i in np.arange(1,101,5)]

print(np.bitwise_and(s[::],s[::-1]))# To Compute the bit-wise AND of two array element-wise(binary representation of integers in input arrays).
print(np.bitwise_and(10,11))

print(np.bitwise_or(s[::],s[::-1]))# To Compute the bit-wise OR of two array element-wise(binary representation of integers in input arrays).
print(np.bitwise_or(10,11))

print(np.bitwise_xor(s[::],s[::-1]))# To Compute the bit-wise XOR of two array element-wise(binary representation of integers in input arrays).
print(np.bitwise_xor(11,10))

x = np.invert(np.array(13, dtype=np.uint8))# To Compute the bit-wise Inversion of an array element-wise.
                                           # It computes the bit-wise NOT of the binary representation of the integers in the input arrays.
                                           # np.uint8 -> It indicates unsigned 8 bit integer
print(x)
print(np.left_shift(5, 2))# To Shift the bits of an integer to the left.
print(np.left_shift(s, 2))

print(np.right_shift(s, 2))# To Shift the bits of an integer to the right.
print(np.right_shift(5, 2))

print(np.binary_repr(5))   # To represent binary form of the input number as a string.
print(np.binary_repr(20))

[ 0  2  2 16  4  2  2 36 40 34 34 40 36  2  2  4 16  2  2  0]
10
[97 95 95 81 93 95 95 61 57 63 63 57 61 95 95 93 81 95 95 97]
11
[97 93 93 65 89 93 93 25 17 29 29 17 25 93 93 89 65 93 93 97]
1
242
20
[  4  24  44  64  84 104 124 144 164 184 204 224 244 264 284 304 324 344
 364 384]
[ 0  1  2  4  5  6  7  9 10 11 12 14 15 16 17 19 20 21 22 24]
1
101
10100


str

In [3]:
'''                #Comparison functions
'''
import numpy as np
a=[i for i in np.arange(1,11)]
print(np.greater(12,40)) # It checks which is 'greater' out of given inputs
print(np.greater(a,5))

print(np.greater_equal(12,40)) # It checks which is 'greater or equal' to out of given inputs
print(np.greater_equal(a,5))

print(np.less(12,40)) # It checks which is 'lesser' out of given inputs
print(np.less(a,5))

print(np.less_equal(12,40)) # It checks which is 'lesser or equal' to out of given inputs
print(np.less_equal(a,5))

print(np.not_equal(12,40)) # It checks whether given inputs are 'not equal'
print(np.not_equal(a,5))

print(np.equal(12,40))# It checks whether given inputs are 'equal'
print(np.equal(a,5))

print(np.logical_and(12,40)) # It compute the AND operation on inputs.
print(np.logical_and(a,5))

print(np.logical_or(12,40)) # It compute the OR operation on inputs.
print(np.logical_or(a,5))

print(np.logical_xor(12,40)) # It compute the XOR operation on inputs.
print(np.logical_xor(a,5))

print(np.logical_not(a)) # It compute the NOT operation on input.
print(np.logical_not(5))

print(np.maximum(12,40)) # It finds the element-wise maximum of array elements.
                         # It compares two arrays and returns a new array containing the element-wise maxima.
print(np.maximum(a,5))

print(np.minimum(12,40))# It finds the element-wise minimum of array elements.
                         # It compares two arrays and returns a new array containing the element-wise minima.
print(np.minimum(a,5))

print(np.fmax(12,40))   # To compute element-wise maximum of array elements. 
                        # This function compare two arrays and returns a new array containing the element-wise maxima.
print(np.fmax(a,5))

print(np.fmin(12,40))   # To compute element-wise minimum of array elements. 
                        # This function compare two arrays and returns a new array containing the element-wise minimum.
print(np.fmin(a,5))

False
[False False False False False  True  True  True  True  True]
False
[False False False False  True  True  True  True  True  True]
True
[ True  True  True  True False False False False False False]
True
[ True  True  True  True  True False False False False False]
True
[ True  True  True  True False  True  True  True  True  True]
False
[False False False False  True False False False False False]
True
[ True  True  True  True  True  True  True  True  True  True]
True
[ True  True  True  True  True  True  True  True  True  True]
False
[False False False False False False False False False False]
[False False False False False False False False False False]
False
40
[ 5  5  5  5  5  6  7  8  9 10]
12
[1 2 3 4 5 5 5 5 5 5]
40
[ 5  5  5  5  5  6  7  8  9 10]
12
[1 2 3 4 5 5 5 5 5 5]


In [4]:
'''
                     #Floating functions
'''
import numpy as np
a=[i for i in np.arange(1,11)]
print(np.isfinite(a)) #returns Boolean values True or False depending on the following: It returns False if x is positive infinity, 
                      # negative infinity or NaN. It returns True in all other cases.
print(np.nan,np.isfinite(np.nan)) 
print(np.inf,np.isfinite(np.inf))
print(np.NINF,np.isfinite(np.NINF))

print(np.isinf(a)) # checks whether a number is infinite or not. (+/- number)
x = np.array([-np.inf, 0., np.inf])
y = np.array([2, 2, 2])
print("Checking for infinity : ", np.isinf(x, y)) 

print(np.isnan(a)) # element-wise whether it is NaN or not and returns the result as a boolean array.
print(np.isnan(x,y))
print(np.isnan(1))
print(np.isnan(0))
print(np.isnan(np.nan), "\n")# not a number
print(np.isnan(np.inf), "\n")# infinity
print(np.isnan(np.NINF), "\n")  # Not a Number is not equivalent to infinity. Defines an alias for negative infinity: 






print(np.isnat(np.datetime64("Nat"))) # we can get the boolean value as true if date defined in a np.datetime64() method is not a time by 
                                        # using numpy.isnat() method.
print(np.isnat(np.datetime64("1998-01-01")))
print(np.fabs(a),',',np.fabs(10)) # used to compute the absolute values element-wise. This function returns the absolute values 
                                    #(positive magnitude) of the data in arr. It always return absolute values in floats.
print(np.signbit(a)) # element – wise check whether the signbit is set or not
print(np.copysign(1.3, -1)) # to change the sign of 2 different arrays or elements.
print(1/np.copysign(0, 1))
print(1/np.copysign(0, -1))
print(np.copysign([-1, 0, 1], -1.1))
print(np.copysign([-1, 0, 1], np.arange(3)-1))
print(np.signbit([1, -23, +34, 11]))
print(np.signbit([-1, 2, -3, -4]))
print(np.signbit(np.copysign([1,-23,+34,11],[-1,2,-3,-4])))


eps = np.finfo(np.float64).eps #finfo- shows machine limits for floating point types
print(eps)
print(np.nextafter(1, 2) == eps + 1) # to return next floating-point value after arr1 towards arr2, element-wise.
print(np.nextafter([1, 2], [2, 1]) == [eps + 1, 2 - eps])

print(np.spacing(a))
print(np.modf(a),np.modf(3.6),np.modf(-10),np.modf(10)) # returns the fractional and integer parts of the number in a two-item tuple.
print(np.ldexp(5, np.arange(4))) #This is also called as inverse of numpy.frexp() function. 
print(np.ldexp(*np.frexp(a)))

print(np.frexp(a)) # returns the mantissa and the exponent of a specified number, as a pair (m,e). 
                    # The mathematical formula for this method is: number = m * 2**e.
print(np.fmod([-3, -2, -1, 1, 2, 3], 2)) # to calculate the Module of the specified given arguments.
print(np.fmod([5, 3], [2, 2.]))

print(np.remainder([-3, -2, -1, 1, 2, 3], 2)) #It returns element-wise remainder of division.
print(np.remainder([1,2,3,4,5],[3,5,1,2,6]))

print(np.floor(a))  # returns the floor of the elements of array
print(np.ceil(a)) #  return the ceil values for each element
print(np.trunc(a)) # returns the truncated value of the elements of array.

[ True  True  True  True  True  True  True  True  True  True]
nan False
inf False
-inf False
[False False False False False False False False False False]
Checking for infinity :  [1 0 1]
[False False False False False False False False False False]
[0 0 0]
False
False
True 

False 

False 

True
False
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] , 10.0
[False False False False False False False False False False]
-1.3
inf
-inf
[-1. -0. -1.]
[-1.  0.  1.]
[False  True False False]
[ True False  True  True]
[ True False  True  True]
2.220446049250313e-16
True
[ True  True]
[2.22044605e-16 4.44089210e-16 4.44089210e-16 8.88178420e-16
 8.88178420e-16 8.88178420e-16 8.88178420e-16 1.77635684e-15
 1.77635684e-15 1.77635684e-15]
(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])) (0.6000000000000001, 3.0) (-0.0, -10.0) (0.0, 10.0)
[ 5. 10. 20. 40.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
(array([0.5   , 0.5   , 0.75  , 0.5   , 0.625 , 0

C:\Users\KIIT\AppData\Local\Temp\ipykernel_20288\385784783.py:34: RuntimeWarning: divide by zero encountered in scalar divide
  print(1/np.copysign(0, 1))
C:\Users\KIIT\AppData\Local\Temp\ipykernel_20288\385784783.py:35: RuntimeWarning: divide by zero encountered in scalar divide
  print(1/np.copysign(0, -1))


In [46]:
'''#Statistical functions
'''
import numpy as np
a=[i for i in np.arange(1,11)]
print(np.amin(a))# Return the minimum of an array or minimum along an axis
print(np.amax(a))# Return the maximum of an array or minimum along an axis
print(np.ptp(a))# Returns the range between minimum and maximum values along a specified axis. 
print(np.percentile(a, 5, axis=0))  # Used to compute the nth percentile of the given data (array elements) along the specified axis.
print(np.median(a))                     # To find median 
print(np.mean(a))                       # To find mean 
print(np.std(a))                        # To find standard deviation
print(np.var(a))                        # To find variance
print(np.average(a))                    # To find average 

1
10
9
1.45
5.5
5.5
2.8722813232690143
8.25
5.5


In [4]:
'''#Math operations:
'''
 
import numpy as np
a=[i for i in np.arange(1,11)]
print(np.add(a,9))              # To add each element with a number
print(np.subtract(2,6))# # To subtract each element with a number
print(np.multiply(a,10)) # To multiply each element with a number
print(np.matmul([[1,0],[0,1]],[[1,2],[3,4]])) # It returns the matrix product of two arrays
print(np.divide(2,5)) # It computes the element-wise division of array elements or any two numbers. 
print(np.logaddexp(a,10)) # to calculate Logarithm of the sum of exponentiations of the inputs.
print(np.logaddexp2(a,10)) # to calculate Logarithm of the sum of exponentiations of the inputs in base-2.
print(np.true_divide(a,10)) # Returns a true division of the inputs, element-wise.
                            # Array element from first array is divided by the elements from second array. 
print(np.floor_divide(a,10)) # Return the largest integer smaller or equal to the division of the inputs. 
                             # It is equivalent to the Python // operator.
print(np.negative(a))#  It is used when we want to compute the negative of array elements. It returns element-wise negative value of an array.
print(np.positive(a))# computes the positive of a number or array element-wise.It returns the element-wise numerical positive for the input array. 
print(np.power(a,3)) # Array element from first array is raised to the power of element from second element
print(np.float_power(a,0.5)) # return a usable result for negative powers and seldom overflow for +ve powers.
print(np.remainder(a,5)) # It returns element-wise remainder of division between two array 
print(np.mod(a,5)) #       It returns element-wise remainder of division between two array arr1 and arr2 i.e. arr1 % arr2 . 
print(np.fmod(a,5)) # returns an array that contains the remainder of the division of the two given input arrays.
print(np.divmod(a,5)) # returns an array showing the element-wise quotient and remainder of the division of two arrays simultaneously.
print(np.absolute(a)) #  calculates the absolute value of the values in a Numpy array. 
print(np.fabs(a)) # returns the absolute values (positive magnitude) of the data.
print(np.rint(a)) # rounds elements of the array to the nearest integer.
print(np.sign(a)) # to indicate the sign of a number element-wise
print(np.heaviside(a,5)) # used to compute the Heaviside step function of an input array passed to it.
print(np.conj(a)) # to conjugate any complex number.The conjugate of a complex number is obtained by changing the 
                                  # sign of its imaginary part. 
print(np.conjugate(a)) # o conjugate any complex number
print(np.exp(a)) #to calculate the exponential values 
print(np.exp2(a))# to calculate 2**x for all x being the array elements.
print(np.log(a)) # computes the natural logarithm of an input array's elements.
print(np.log2(a))# to calculate Base-2 logarithm of x where x belongs to all the input array elements.
print(np.log10(a)) # returns the base-10 logarithm of a number.
print(np.expm1(a)) # to calculate exponential of all the elements subtracting 1 from all the input array elements.
print(np.log1p(a)) #  a complex analytical function that has a branch cut [-inf, -1] and is continuous from above on it. 
print(np.sqrt(a))         # To find Squareroot
print(np.square(a))       # To find square
print(np.cbrt(a))         # To find cuberoot
print(np.reciprocal(a))   # To find reciprocal
print(np.gcd(a,a))        # To find HCF
print(np.lcm(a,10))       # To find LCM 

[10 11 12 13 14 15 16 17 18 19]
-4
[ 10  20  30  40  50  60  70  80  90 100]
[[1 2]
 [3 4]]
0.4
[10.0001234  10.00033541 10.00091147 10.00247569 10.00671535 10.01814993
 10.04858735 10.12692801 10.31326169 10.69314718]
[10.00281502 10.00562455 10.01122726 10.02236781 10.04439412 10.08746284
 10.169925   10.32192809 10.5849625  11.        ]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0 0 0 0 0 0 0 0 0 1]
[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]
[ 1  2  3  4  5  6  7  8  9 10]
[   1    8   27   64  125  216  343  512  729 1000]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[1 2 3 4 0 1 2 3 4 0]
[1 2 3 4 0 1 2 3 4 0]
[1 2 3 4 0 1 2 3 4 0]
(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2], dtype=int32), array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32))
[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  

In [ ]:
'''
Numpy type

C type

Description

numpy.bool_

bool

Boolean (True or False) stored as a byte

numpy.byte

signed char

Platform-defined

numpy.ubyte

unsigned char

Platform-defined

numpy.short

short

Platform-defined

numpy.ushort

unsigned short

Platform-defined

numpy.intc

int

Platform-defined

numpy.uintc

unsigned int

Platform-defined

numpy.int_

long

Platform-defined

numpy.uint

unsigned long

Platform-defined

numpy.longlong

long long

Platform-defined

numpy.ulonglong

unsigned long long

Platform-defined

numpy.half / numpy.float16

Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

numpy.single

float

Platform-defined single precision float: typically sign bit, 8 bits exponent, 23 bits mantissa

numpy.double

double

Platform-defined double precision float: typically sign bit, 11 bits exponent, 52 bits mantissa.

numpy.longdouble

long double

Platform-defined extended-precision float

numpy.csingle

float complex

Complex number, represented by two single-precision floats (real and imaginary components)

numpy.cdouble

double complex

Complex number, represented by two double-precision floats (real and imaginary components).

numpy.clongdouble

long double complex

Complex number, represented by two extended-precision floats (real and imaginary components).

'''